 DATA SEGMENT
 PORTA EQU 60H
 PORTB EQU 62H
 PORTC EQU 64H
 CWR EQU 66H
 DATA ENDS
 
CODE    SEGMENT 
   MOV AX,DATA
   MOV DS,AX
   ORG 0000H

START:
    MOV AL,82H			; PORT A OUTPUT. PORT B INPUT, MODE 0
    MOV DX,CWR			; SETTING CONTROL REGISTER
    OUT DX,AL
    
   L1:
   MOV DX,PORTB
   IN AL,DX				; INPUT FROM PORT B
   SHL AL, 01H			; LEFT SHIFT WITH CARRY
   JNC LEDOFF			; LED OFF IF CARRY IS ZERO
   SHL AL, 01H			; LEFT SHIFT WITH CARRY
   JNC LEDOFF			; LED OFF IF CARRY IS ZERO
   MOV DX, PORTA
   MOV AL, 80H			; SETTING 7TH BIT ONE AND REST BIT ZERO
   OUT DX, AL				; OUTPUT TO PORT A
   JMP L1

   LEDOFF:
   MOV DX,PORTA
   MOV AL, 00H			; SETTING ALL BITS AS ZERO
   OUT DX,AL				; OUTPUT TO PORT A
   JMP L1
CODE    ENDS
END








.MODEL SMALL			; SIMPLIFIED SEGMENT DEFINATION
.DATA
 PORTA EQU 60H
 PORTB EQU 62H
 PORTC EQU 64H
 CWR EQU 66H
 
.CODE
.STARTUP
   MOV AX,@DATA
   MOV DS,AX
   ORG 0000H

START:
    MOV AL,82H			; PORT A OUTPUT. PORT B INPUT, MODE 0
    MOV DX,CWR			; SETTING CONTROL REGISTER
    OUT DX,AL
    
   L1:
   MOV DX,PORTB
   IN AL,DX				; INPUT FROM PORT B
   SHL AL, 01H			; LEFT SHIFT WITH CARRY
   JNC LEDOFF			; LED OFF IF CARRY IS ZERO
   SHL AL, 01H			; LEFT SHIFT WITH CARRY
   JNC LEDOFF			; LED OFF IF CARRY IS ZERO
   MOV DX, PORTA
   MOV AL, 80H			; SETTING 7TH BIT ONE AND REST BIT ZERO
   OUT DX, AL				; OUTPUT TO PORT A
   JMP L1

   LEDOFF:
   MOV DX,PORTA
   MOV AL, 00H			; SETTING ALL BITS AS ZERO
   OUT DX,AL				; OUTPUT TO PORT A
   JMP L1
.EXIT
END
