;====================================================================
; Main.asm file generated by New Project wizard
;
; Created:   Tue Nov 21 2021
; Processor: 8086
; Compiler:  MASM32
;
; Before starting simulation set Internal Memory Size 
; in the 8086 model properties to 0x10000
;====================================================================

CODE    SEGMENT PUBLIC 'CODE'
        ASSUME CS:CODE

START:
	
	; --> Used to Divide 4Mhz Clock to 2000 so that we get 2Khz Output
        MOV AL, 00110101b	; 00 [counter 0], 11[ 2 byte data], 010 [ with mod 2], 1 [BCD] 
	OUT 6Fh, AL		; configure the counter 0 of 8253
	
	; --> Pulse Wave  :: MOD 2 of 8253
	MOV AL, 01110101b	; 01 [counter 1], 11[ 2 byte data], 010 [ with mod 2], 1 [BCD]
	OUT 6Fh, AL		; configure the counter 1 of 8253
	
	; --> Square Wave :: MOD 3 of 8253
	MOV AL, 10110111b	; 10 [counter 2], 11[ 2 byte data], 011 [ with mod 3], 1 [BCD]
	OUT 6Fh, AL		; configure the counter 2 of 8253
	
	MOV AL, 00h		
	OUT 69h, AL		; Send first byte of Counter 0
	MOV AL, 20h		
	OUT 69h, AL		; Send second byte of Counter 0
	;;--> Counter0 : 2000h	; send BCD 2000 to counter 0
	
	MOV AL, 00h		
	OUT 6Bh, AL		; Send first byte of Counter 1
	MOV AL, 01h		
	OUT 6Bh, AL		; Send second byte of Counter 1
	;;--> Counter1	: 100h  ; send BCD 100 to counter 1
	
	
	MOV AL, 00h		
	OUT 6Dh, AL		; Send first byte of Counter 1
	MOV AL, 20h		
	OUT 6Dh, AL		; Send second byte of Counter 1
	;;--> Counter2	: 2000h ; send BCD 2000 to counter 2
	

ENDLESS:
        JMP ENDLESS
CODE    ENDS
        END START;====================================================================
; Main.asm file generated by New Project wizard
;
; Created:   Tue Dec 3 2019
; Processor: 8086
; Compiler:  MASM32
;
; Before starting simulation set Internal Memory Size 
; in the 8086 model properties to 0x10000
;====================================================================

CODE    SEGMENT PUBLIC 'CODE'
        ASSUME CS:CODE

START:
	
	; --> Used to Divide 4Mhz Clock to 2000 so that we get 2Khz Output
        MOV AL, 00110101b	; 00 [counter 0], 11[ 2 byte data], 010 [ with mod 2], 1 [BCD] 
	OUT 6Fh, AL		; configure the counter 0 of 8253
	
	; --> Pulse Wave  :: MOD 2 of 8253
	MOV AL, 01110101b	; 01 [counter 1], 11[ 2 byte data], 010 [ with mod 2], 1 [BCD]
	OUT 6Fh, AL		; configure the counter 1 of 8253
	
	; --> Square Wave :: MOD 3 of 8253
	MOV AL, 10110111b	; 10 [counter 2], 11[ 2 byte data], 011 [ with mod 3], 1 [BCD]
	OUT 6Fh, AL		; configure the counter 2 of 8253
	
	MOV AL, 00h		
	OUT 69h, AL		; Send first byte of Counter 0
	MOV AL, 20h		
	OUT 69h, AL		; Send second byte of Counter 0
	;;--> Counter0 : 2000h	; send BCD 2000 to counter 0
	
	MOV AL, 00h		
	OUT 6Bh, AL		; Send first byte of Counter 1
	MOV AL, 01h		
	OUT 6Bh, AL		; Send second byte of Counter 1
	;;--> Counter1	: 100h  ; send BCD 100 to counter 1
	
	
	MOV AL, 00h		
	OUT 6Dh, AL		; Send first byte of Counter 1
	MOV AL, 20h		
	OUT 6Dh, AL		; Send second byte of Counter 1
	;;--> Counter2	: 2000h ; send BCD 2000 to counter 2
	

ENDLESS:
        JMP ENDLESS
CODE    ENDS
        END START
