;====================================================================
; Main.asm file generated by New Project wizard
;
; Created:   Thu Oct 7 2021
; Processor: 8086
; Compiler:  MASM32
;
; Before starting simulation set Internal Memory Size 
; in the 8086 model properties to 0x10000
;====================================================================
 DATA SEGMENT 
      
      PORTA EQU 60H
      PORTB EQU 62H
      PORTC EQU 64H
      CWR   EQU  66H
      
DATA ENDS

CODE    SEGMENT PUBLIC 'CODE'
        ASSUME CS:CODE

START:
	 MOV AX, DATA
	 MOV DS, AX

	MOV AL, 10000010b			; Configure 8255, MODE 0 port B input, port A output, port C output
	OUT CWR, AL
	
	MOV AL, 0FFH
	OUT PORTA, AL			; INITIAL DISPLAY
	CALL DELAY
	
ENDLESS:

	   IN AL, PORTB			; read button states

	   AND AL, 00000011b		; CHECK FOR SWITCH1 AND SWITCH 2 from PORT B
	   JPE ERROR				; CHECK PARITY IF BOTH SWITCH ON PARITY =1
	   
	   TEST AL, 00000001b		;CHECK IF SWITCH A IS PRESSED
	   JZ ODD
	   
	   MOV AL, 11000000b		;0
	   OUT PORTA, AL
	   CALL DELAY
		  
	  MOV AL, 10100100B		;2
	  OUT PORTA, AL
	  CALL DELAY
		  
	  MOV AL, 10011001B		;4
	  OUT PORTA, AL
	  CALL DELAY
	  
	  MOV AL, 10000010B		;6
	  OUT PORTA, AL
	  CALL DELAY
	  
	  MOV AL, 10000000B		;8
	  OUT PORTA, AL
	   CALL DELAY
	   
	   JMP ENDLESS
	   ODD:
		  MOV AL, 11111001B	;1
		  OUT PORTA, AL
		  CALL DELAY
		  
		  MOV AL, 10110000B	;3
		  OUT PORTA, AL
		  CALL DELAY
		  
		  MOV AL, 10010010B	;5
		  OUT PORTA, AL
		  CALL DELAY
		  
		  MOV AL, 11111000B	;7
		  OUT PORTA, AL
		  CALL DELAY
		  
		  MOV AL, 10010000B	;9
		  OUT PORTA, AL
		  CALL DELAY
		  
		  JMP ENDLESS
	   
	   ERROR:
		  MOV AL, 10000110B	;E
		  OUT PORTA, AL
		  JMP ENDLESS
	
	DELAY PROC NEAR
	     MOV CX,0EF36H						; Delay
	     l1:
		  LOOP l1
	     RET
        DELAY ENDP


CODE    ENDS
        END START
